### ISSUE TITLE
ラベルＱＲのラベルシリアルＮｏの内容に関して

### ISSUE THREAD

**Issue by jms-fukuta** [jms-web/ADLIV#31]
ラベルＱＲの内容記載内容に不具合があります
ラベルシリアルの取得でＰＣ名の右４Ｂｙｔｅを取得してＱＲの内容を生成する仕様だが、
３Ｂｙｔｅ目から４Ｂｙｔｅを切り出しして表示しています

通常はPC名は、AD-1234になるので、右４Byteで1234を取得してセットしないと行けない

**Comment by jms-arai** [comment]
PC名をAD1234のような形式と認識しており、プログラム上で
３桁目から４桁分を取得していました。
PC名の右から４バイト取得するように修正します。
