### ISSUE TITLE
BHTの同期に関しての不具合

### ISSUE THREAD

**Issue by jms-fukuta** [jms-web/ADLIV#32]
【現象】
①PCにて、初期重量の読取モード無で、かんばんQRを読取ってラベルを発行し、ラベル照合待ち状態にする
②BHTにて社員ｓQRを読取って、かんばんQRを読取し、PCに問い合わせ
③BHTでPCデータを受信した結果、「トレースID違い」エラーが発生

【考えられる原因】
PCから取得したデータが、PCで読取られたトレースIDになっていないのでは？

**Comment by jms-arai** [comment]
①の時点でBHT向けにFTPラベル発行履歴情報ファイル（V004_LABEL_HAKKO.dat）を出力しており、
③でBHTが上記ファイルを読み込んだ際にトレースID違いでエラーを発生させているとの認識ですが、
こちらにてかんばんQRを読み込み、FTPラベル発行履歴情報ファイルを確認しましたが、QRのトレースIDと一致する値を出力していました。

こちらで確認したい内容としては、
①かんばんQRの中にあるトレースIDと、V004_LABEL_HAKKO.datの中のトレースIDが一致しているか？
　※これが一致していないからエラーになっているかとは思いますが。。。
②かんばんQRの中にあるトレースIDの切り出しが間違っている？またはBHTとPCで取得位置が違う？
　※太田くんよりもらったエスアイ標準の関数を使用しているため考えにくいですが。。
③現地で起きたエラーなのであれば、BHTとPCのFTPの共有フォルダは端末ごとに
　ディレクトリが分かれているか？
　※PC１台、BHT１台で確認しているのであれば関係ないですが、
　　PC複数台、BHT複数台で、同じディレクトリを見ているとなると、
　　ファイル名は同じなので上書きされた可能性もあります

今のところ原因が不明です。
Slackでも回答しましたが、エラーが発生したかんばん（PDF等画像ファイルでいいです）を
いただけないでしょうか？
